### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by rpelaez** [TiesNetwork/ties.db#16]
When I execute tiesdb it raises this exception:
CompilerOracle: inline org/apache/cassandra/utils/vint/VIntCoding.encodeVInt (JI)[B
Exception in thread "TiesServiceDaemon:TEST" java.lang.RuntimeException: Can't create TiesDB schema
	at network.tiesdb.schema.impl.ethereum.TiesSchemaFactoryImpl.createSchema(TiesSchemaFactoryImpl.java:42)
	at network.tiesdb.service.impl.elassandra.TiesServiceImpl.initTiesSchema(TiesServiceImpl.java:103)
	at network.tiesdb.service.impl.elassandra.TiesServiceImpl.initInternal(TiesServiceImpl.java:94)
	at network.tiesdb.service.impl.elassandra.TiesServiceDaemonImpl.run(TiesServiceDaemonImpl.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: network.tiesdb.exception.TiesConfigurationException: Invalid contract address: contract binary missmatch
	at network.tiesdb.schema.impl.ethereum.impl.TiesSchemaEthereum.<init>(TiesSchemaEthereum.java:50)
	at network.tiesdb.schema.impl.ethereum.TiesSchemaFactoryImpl.createSchema(TiesSchemaFactoryImpl.java:40)
	... 4 more

**Comment by rpelaez** [comment]
The last line of log show this: 2018-08-12 13:56:09,436 INFO  [elasticsearch[127.0.0.1][clusterService#updateTask][T#1]] CassandraGatewayService.java:81 clusterStateProcessed [127.0.0.1] cassandra ring block released

**Comment by ya-enot** [comment]
Could you please check settings at conf/tiesdb.yaml in the node installation directory. This error could be caused by improper configuration of your node. The configuration of "schema: !!SchemaEthereum" should be:
      endpointUrl: http://localhost:8545
      contractAddress: 0x22D1B55eBb5BcD17084C3C9D690056875263fEc1

**Comment by rpelaez** [comment]
This is the config:
# TiesDB config YAML
#saveSettingsOnStop: true
config:
  TEST: !!ServiceTiesDB
    schema: !!SchemaEthereum
      endpointUrl: http://localhost:8545
      contractAddress: 0x22D1B55eBb5BcD17084C3C9D690056875263fEc1
    transports:
      - !!TransportWebSocket
        #handler: !!JsonHandler
        #  charset: UTF-8
        handler: !!HandlerV0R0
        workerThreadsCount: 8
        serviceAddress: localhost
        servicePort: 8080
        #security:
        #  securedSocket: false

**Comment by ya-enot** [comment]
Please check that your local ethereum client (e.g. geth) serving the 8545 port is connected to Rinkeby network.

**Comment by rpelaez** [comment]
![captura de pantalla 2018-08-13 a las 18 29 04](https://user-images.githubusercontent.com/1374732/44044731-cf627314-9f26-11e8-9e42-342a0b09eb0e.png)

Yes it's in the 8545 port. How I can test the Server? There is a UI? Regards

**Comment by ya-enot** [comment]
Is your geth connected to Rinkeby network?
We are working on creation of the db testing tools. You can use https://uiproto.tiesdb.com for schema management.

**Comment by ya-enot** [comment]
Your geth client should be synced up to at least 1683229 rinkeby block for succesfull launch. And should be kept syncing during operation.

**Comment by rpelaez** [comment]
OK! while I'm synchronizing I'm trying the UI, very nice work guys! 
Many thanks!

One question, how I can set a String field default value? 
![captura de pantalla 2018-08-25 a las 19 41 30](https://user-images.githubusercontent.com/1374732/44621016-42df5880-a89f-11e8-97d3-dc8d2dd7ee21.png)

**Comment by ya-enot** [comment]
It seems like a bug in geth operating in "fast" mode. You can run geth in "light" mode (it takes approx. 30 minutes for synchronization) or "full" mode, install it from an appropriate [bundle](https://ethereum.github.io/go-ethereum/downloads/), run it in [docker](https://ethereum.github.io/go-ethereum/install/#run-inside-docker-container) or [compile](https://ethereum.github.io/go-ethereum/install/#build-it-from-source-code) it from sources.
For running geth in light mode use this command:
```
geth --rinkeby --datadir .rinkeby --cache 512 --rpc --rpcaddr 127.0.0.1 --syncmode "light"
```
