### ISSUE TITLE
Docs, replace geth fast syncmode

### ISSUE THREAD

**Issue by RdeWilde** [TiesNetwork/ties.db#19]
`geth --rinkeby --datadir .rinkeby --cache 512 --rpc --rpcaddr 127.0.0.1 --fast` 

change it to

`geth --rinkeby --datadir .rinkeby --cache 512 --rpc --rpcaddr 127.0.0.1 --syncmode "fast"`

https://github.com/TiesNetwork/ties.db/releases

**Comment by ya-enot** [comment]
Release description updated
